### PR TITLE
Namespace tests

### PR DESCRIPTION
**Pull request by AlexWeinstein92**

### CODE REVIEW

**Review by reid-spencer — CHANGES_REQUESTED** [review]
The examples folder was recently removed from riddl and now has its own repository. So, I can't approve this PR. You have two choices:
* Move these files to the testkit/src/test directory with the riddl in the "testkit/src/test/input" directory, or
* add these things to riddl-examples repository
The latter is preferred.

**Comment by reid-spencer** [comment]
The "conf files" change LGTM

**Comment by reid-spencer** [comment]
This PR is so badly broken and large I'm inclined to just close it.

**Comment by AlexWeinstein92** [comment]
@reid-spencer this PR is no longer 'badly broken'. It is working locally, but it uses `ASimpleTestCommand` which I didn't realize was in the `test` folder of `commands` subproject, and so not picked up on when not running locally. It depends on `test/resources/META_INF` so I am not sure about what to do from here on.

**Review by reid-spencer — APPROVED** [review]

**Pull request merged**
